title:            Sigit Purwadi's Official Blog
description:      "Just another personal official blog"
logo:             S-icon.png
disqus_shortname: spurwadi

# Assign a default image for your site's header and footer
default_bg:       default_bg1.jpg
search:           true
share:            true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true

# Specify the average Words per minute. If not defined, 180 will be used
wpm:			  200

# Turn on or off the fin animations in the header and footer
triangleheader:	  true
animated_fins:	  true

# Specify the fin color in RGB value
fin_color:        "255,255,255"

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:       		  http://blog.purwadi.web.id

# Owner/author information
owner:
  name:           Sigit Purwadi
  avatar:         sigit.jpg
  email:          sgt2426@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Sigit Purwadi is an &lt;a href=&quot;https://en.wikipedia.org/wiki/Educational_technology&quot; target=&quot;_blank&quot;&gt;Education Engineer&lt;/a&gt; and a blogger based in &lt;a href=&quot;http://www.indonesia.travel/destinations/destination/33/di-yogyakarta&quot; target=&quot;_blank&quot;&gt;Yogyakarta, Indonesia&lt;/a&gt;. His interests are anything that&#8217;s related to art, science, and logic, from art and logic itself to design, photography, and programming languages to music to physics to engineering to philosophy.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        S_Purwadi
  facebook:       SigitOfficial
  github:         spurwadi
  linkedin:       https://id.linkedin.com/in/spurwadi
  instagram:      S_Purwadi
  flickr:         s_purwadi      
  # soundcloud:     S_Purwadi
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/111158361004969556148

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-61535015-2
google_verify:     oEfgtpe8RoaSXmpUaa-vPjD2D-l6jv5uFiJB7mFOyFA
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:       732F0388A96A6CD82BBC5006CF4E2A49

# Links to include in footer navigation
# For external links add external: true
links:
  - title: <i class="icon-home"></i> Home
    url: /
    # *icon: home
  - title: <i class="icon-beaker"></i> Portfolio
    url: http://sigit.purwadi.web.id
    external: true
  - title: <i class="icon-book"></i> Documentation
    url: /documentation
  - title: <i class="icon-archive"></i> Categories
    url: /categories
  - title: <i class="icon-tag"></i> Tags
    url: /tags
  - title: <i class="icon-info"></i> About Me
    url: /sigit-purwadi

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Jakarta
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://blog.purwadi.web.id/'
  relativeLinks: 'http://blog.purwadi.web.id/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "type"
        field:
          element: "select"
          label: "Select Post Type"
          placeholder: "Choose your type"
          options:
            - name: "Standard"
              value: 
            - name: "Quote"
              value: quote
            - name: "Status"
              value: status
            - name: "Photo"
              value: photo
            - name: "Video"
              value: video
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
            - name: "Interesting"
              value: interesting
            - name: "Status"
              value: status
            - name: "Quotes"
              value: quotes
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "imagecredit"
        field:
          element: "text"
          label: "Image Credit"
          placeholder: "some guy"
      - name: "imagecreditlink"
        field:
          element: "text"
          label: "Credit link for the image"
          placeholder: "http://somewebsite.com"
      - name: "video"
        field:
          element: "text"
          label: "Insert Youtube Link"
          placeholder: "http://youtube.com/somevideo"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
